name: Publish

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run:
          python3 -m pip install -r requirements.txt
      - name: Run
        run:
          python3 -m src.main